### ISSUE TITLE
How much time to compile ?

### ISSUE THREAD

**Issue by Vinetos** [SalonDesDevs/pate2crabe#1]
I tried to compile the project as explained on the non-existent README.
It's been 3 weeks now and my pc seems to have come alive ! Please help me.

Three days ago, I heard him talking while I was sleeping, I think he was saying that he wanted to download the whole internet and conquer the world. 
Aled

**Comment by Cackbone** [comment]
:stonks:

**Comment by shika-blyat** [comment]
xDDDDD

**Comment by shika-blyat** [comment]
Closing because t'es pd

**Comment by cchudant** [comment]
Everything is normal. Just follow the instructions.
